### ISSUE TITLE
Fails On Start After Python3.7 Upgrade

### ISSUE THREAD

**Issue by ShinyNewLove** [NatTupper/Discline#21]
Distro: Manjaro (Arch) 
Linux: 4.14.109-1
Python: 3.7.2
Install: Git clone, python install and pip3 install
Branch: rewrite

After executing "python3 dline", I get this error: 

```
Checking for updates...
Already up to date!

Starting...
Exception ignored in: <function ClientSession.__del__ at 0x7febb0195400>
Traceback (most recent call last):
  File "/home/shiny/.local/lib/python3.7/site-packages/aiohttp/client.py", line 305, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1640, in call_exception_handler
  File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
Exception ignored in: <function BaseConnector.__del__ at 0x7febb01abc80>
Traceback (most recent call last):
  File "/home/shiny/.local/lib/python3.7/site-packages/aiohttp/connector.py", line 281, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1640, in call_exception_handler
  File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
```

**Comment by ShinyNewLove** [comment]
I've uninstalled and reinstalled all of the related packages and haven't had any luck clearing this issue.
It is the consensus among my peers that ``` __del__ ``` shouldn't be called anymore, but replaced with ``` __enter__ ``` / ``` __exit__ ``` in a ``` with ``` statement.  However, I don't specialize in Python, so I wouldn't know operable library procedure.
