### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Merith-TK** [NatTupper/Discline#22]
**Describe the bug**
```
chronos@localhost ~ $ pip3 install dline
Collecting dline
  Using cached https://files.pythonhosted.org/packages/24/b2/57a4313cb2a101e87a093c82bd49064ed01c0ad195de7087c7f22c6b3dd0/dline-2.4.1.tar.gz
Requirement already satisfied: asyncio in /usr/local/lib/python3.7/site-packages (from dline) (3.4.3)
Requirement already satisfied: blessings in /usr/local/lib/python3.7/site-packages (from dline) (1.7)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/site-packages (from dline) (5.1)
Collecting mistletoe==0.6.2 (from dline)
  Using cached https://files.pythonhosted.org/packages/0a/5f/8d4acb75a52ebeb0e6cfdb13e1bf37a3cb0ccab93321ae060f2df21d8b36/mistletoe-0.6.2-py3-none-any.whl
Collecting discord.py==1.0.0a (from dline)
  Could not find a version that satisfies the requirement discord.py==1.0.0a (from dline) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.8, 0.16.9, 0.16.10, 0.16.11, 0.16.12)
No matching distribution found for discord.py==1.0.0a (from dline)* Installation type (repo install or pip)
```
* Branch of dline you're using
* Python version `3.7.1`
* Linux distribution `3.8.11`

**To Reproduce**
Be me, 
use a XE500C21 chromebook
install from any method
**Expected behavior**
actually install
**Additional context**
NNot going to use sudo because chromebrew is borked for sudo

**Comment by Merith-TK** [comment]
Fixed by setting the setup.py requirement for discord to a actual discord version. Now I have a issue with async

**Comment by Merith-TK** [comment]
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/dline", line 11, in <module>
    load_entry_point('dline==2.4.1', 'console_scripts', 'dline')()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/dline/__init__.py", line 1, in <module>
    from dline.__main__ import main
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/dline/__main__.py", line 13, in <module>
    if not check_versions():
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/dline/utils/version.py", line 5, in check_versions
    import discord
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```
