### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by THEWHITEBOY503** [NatTupper/Discline#23]
Hi
As per the README.MD: here's the stuff.
OS: Debian GNU/Linux 10 (buster) x86_64
Terminal: konsole
Font: Font: [KDE], Noto Sans Regular 10 [GTK2], Noto Sans 10 [GTK3
Python Version: 3.7
How to reproduce: 
1. put a token file in the directory with the dline stuff (call it token) and paste the discord token in there
2. dline --token-path token
3. (probably) get this:
```
conner@connerdebpc:~/Downloads/dline$ dline --token-path token
Checking for updates...
Already up to date!

Starting...
ERROR: default_guild not found!
Task exception was never retrieved
future: <Task finished coro=<Client._run_event() done, defined at /home/conner/.local/lib/python3.7/site-packages/discord/client.py:240> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/home/conner/.local/lib/python3.7/site-packages/discord/client.py", line 557, in run
    loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/conner/.local/lib/python3.7/site-packages/discord/client.py", line 242, in _run_event
    await coro(*args, **kwargs)
  File "/home/conner/.local/lib/python3.7/site-packages/dline/__main__.py", line 95, in on_ready
    raise KeyboardInterrupt
KeyboardInterrupt
conner@connerdebpc:~/Downloads/dline$
```

Thx in advance.

**Comment by taylorjtamu** [comment]
Did you:
Run dline --copy-skeleton to get a template config
Edit ~/.config/dline/config.yaml to your choosing

I had similar myself, but just had to set the default_guild and default_channel to something from the list of servers/channels I'm actually a member of.

**Comment by THEWHITEBOY503** [comment]
removed the default guild and channel, now i get this error:
```
conner@connerdebpc:~/Downloads/dline$ python3.7 dline
Checking for updates...
Already up to date!

Starting...
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f57fbc853c8>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f57fbb4a828>, 86622.503943581)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f57fbc85860>
conner@connerdebpc:~/Downloads/dline$
```

don't get why none of the like 3 discord CLIs i've attempted to use have worked. I'm either dumb or I just have bad luck.


EDIT: forgot to put --token-path token. I still get the same error as in the opening comment, any other ideas?
